all:
	g++ -o redis_client -Wall redis_client.cpp -lpthread ../libhiredis.a libreactor.a libcommon.a liblog4cplus.a -I../ -I/home/ops/dev_tools/imserver/reactor/include -I/home/ops/dev_tools/imserver/reactor/include/msgpack -std=c++11	
