all:
	g++ -o ex01 ex01.cpp -I./jsoncpp jsoncpp/jsoncpp.cpp 
	g++ -o ex_file ex_file.cpp -I./jsoncpp jsoncpp/jsoncpp.cpp
	g++ -o array_file array_file.cpp -I./jsoncpp jsoncpp/jsoncpp.cpp
	g++ -o write_json write_json.cpp -I./jsoncpp jsoncpp/jsoncpp.cpp

clean:
	rm -rf ex01 ex_file array_file write_json
