all:
	g++ -o ex01 ex01.cpp -I../include ../libjsoncpp.a
	g++ -o ex_file ex_file.cpp -I../include ../libjsoncpp.a
	g++ -o array_file array_file.cpp -I../include ../libjsoncpp.a
	g++ -o write_json write_json.cpp -I../include ../libjsoncpp.a

clean:
	rm -rf ex01 ex_file array_file write_json
