all:
	g++ -o ex01 ex01.cpp -I/Users/diwh/GitHub/cereal/include/ -std=c++11
	g++ -o ex02 ex02.cpp -I/Users/diwh/GitHub/cereal/include -std=c++11
	g++ -o ex03_stl ex03_stl.cpp -I/Users/diwh/GitHub/cereal/include -std=c++11

clean:
	rm -rf ex01 ex02 ex03_stl 
